# Generated by Django 3.1.1 on 2021-09-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='org_email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='org_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='skills',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
